/**
 * TEMPLATES_DIRECTORY_NAME
 * The name of the directory that encapsulates the templates used by a single Codotype Generator
 */
export const TEMPLATES_DIRECTORY_NAME: string = "templates";

/**
 * OUTPUT_DIRECTORY
 * The directory in CWD that stores the files generated by the Plugin + Runtime
 */
export const OUTPUT_DIRECTORY: string = ".codotype-out";

/**
 * CODOTYPE_ARTIFACTS_DIRECTORY
 * The directory inside the a Project's output that stores the codotype-project.json file
 */
export const CODOTYPE_ARTIFACTS_DIRECTORY: string = ".codotype";

/**
 * MODULES_ROOT
 * Constant used to import Plugin modules stored in a Node package
 */
export const MODULES_ROOT: string = "node_modules";

/**
 * PLUGIN_DISTRIBUTABLE_DIR
 * The directory that encapsulates the distributable Plugin metadata + generators + templates
 */
export const PLUGIN_DISTRIBUTABLE_DIR: string = "dist";

/**
 * PLUGIN_METADATA_FILENAME
 * The file inside the Plugin distribution directory that encapsulates the Plugin's metadata
 */
export const PLUGIN_METADATA_FILENAME: string = "meta.js";
