const assert = require('chai').assert;

// const blueprint = require('@codotype/blueprints/lib/todo-list.json')
// const { buildDefault } = require('../lib/buildDefault')


// // CLEANUP - write some ACTUAL tests
// blueprint.schemas.forEach((schema) => {
//   const defaultObject = buildDefault({
//     schema: schema,
//     schemas: blueprint.schemas
//   })

//   console.log(defaultObject)
// })


// // // //

// TODO - build this out a bit more

// describe('/lib/buildDefault.js', () => {
//   describe('sign valid token', () => {
//     it('verify signed JWT should equal original payload', () => {
//       // Stores the token generated by jwt.sign(...)
//       let token = jwt.sign(JWT_PAYLOAD);

//       // Verifies the payload
//       let verify_payload = jwt.verify(token);

//       // Asserts equality of original payload and signed/verified payload
//       // assert.equal(JWT_PAYLOAD.id, verify_payload.id);
//       assert.equal(JWT_PAYLOAD.email, verify_payload.email);
//     });
//   });
// });
