// Datattype IDs
const DATATYPE_STRING = 'STRING'
const DATATYPE_STRING_SELECT = 'STRING_SELECT'
const DATATYPE_STRING_ARRAY = 'STRING_ARRAY'
const DATATYPE_NUMBER = 'NUMBER'
const DATATYPE_INTEGER = 'INTEGER'
const DATATYPE_FLOAT = 'FLOAT'
const DATATYPE_DOUBLE = 'DOUBLE'
const DATATYPE_BOOLEAN = 'BOOLEAN'
const DATATYPE_BOOLEAN_GROUP = 'BOOLEAN_GROUP'
const DATATYPE_DATE = 'DATE'
const DATATYPE_TIME = 'TIME'
const DATATYPE_DATETIME = 'DATETIME'
const DATATYPE_JSON = 'JSON'

module.exports = {
  DATATYPE_NUMBER,
  DATATYPE_INTEGER,
  DATATYPE_FLOAT,
  DATATYPE_DOUBLE,
  DATATYPE_STRING,
  DATATYPE_STRING_ARRAY,
  DATATYPE_STRING_SELECT,
  DATATYPE_BOOLEAN,
  DATATYPE_DATE,
  DATATYPE_TIME,
  DATATYPE_DATETIME,
  DATATYPE_JSON
}