// Datattype IDs
const DATATYPE_STRING = 'STRING' // Supported DBs?
const DATATYPE_TEXT = 'TEXT' // Supported DBs?
const DATATYPE_STRING_SELECT = 'STRING_SELECT' // Supported DBs?
const DATATYPE_STRING_ARRAY = 'STRING_ARRAY' // Supported DBs?
const DATATYPE_INTEGER = 'INTEGER' // Supported DBs?
const DATATYPE_FLOAT = 'FLOAT' // Supported DBs?
const DATATYPE_DOUBLE = 'DOUBLE' // Supported DBs?
const DATATYPE_BOOLEAN = 'BOOLEAN'// Supported DBs?
const DATATYPE_DATE = 'DATE' // Supported DBs?
const DATATYPE_TIME = 'TIME' // Supported DBs?
const DATATYPE_DATETIME = 'DATETIME' // Supported DBs?
const DATATYPE_JSON = 'JSON' // Supported DBs?

module.exports = {
  DATATYPE_INTEGER,
  DATATYPE_FLOAT,
  DATATYPE_DOUBLE,
  DATATYPE_STRING,
  DATATYPE_TEXT,
  DATATYPE_STRING_ARRAY,
  DATATYPE_STRING_SELECT,
  DATATYPE_BOOLEAN,
  DATATYPE_DATE,
  DATATYPE_TIME,
  DATATYPE_DATETIME,
  DATATYPE_JSON
}