const RELATION_TYPE_BELONGS_TO = 'BELONGS_TO'
const RELATION_TYPE_HAS_ONE = 'HAS_ONE'
const RELATION_TYPE_HAS_MANY = 'HAS_MANY'

module.exports = {
 RELATION_TYPE_BELONGS_TO,
 RELATION_TYPE_HAS_ONE,
 RELATION_TYPE_HAS_MANY
}