const RELATION_TYPE_BELONGS_TO = 'BELONGS_TO'
const RELATION_TYPE_HAS_ONE = 'HAS_ONE'
const RELATION_TYPE_HAS_MANY = 'HAS_MANY'
const RELATION_TYPE_HAS_AND_BELONGS_TO_MANY = 'HAS_AND_BELONGS_TO_MANY'

module.exports = {
 RELATION_TYPE_BELONGS_TO,
 RELATION_TYPE_HAS_ONE,
 RELATION_TYPE_HAS_MANY,
 RELATION_TYPE_HAS_AND_BELONGS_TO_MANY
}