import {
    ConfigurationGroup,
    ConfigurationGroupProperty,
    OptionType,
} from "../../types";

// // // //

export const ComponentBuilderConfigurationGroupProperty: ConfigurationGroupProperty = {
    label: "Component",
    identifier: "components",
    description: "Define the component data",
    type: OptionType.COLLECTION,
    defaultValue: [],
    icon:
        "https://res.cloudinary.com/codotype/image/upload/v1558931014/product-logos/twitter-512.png",
    enabled: true,
    required: false,
    allowDisable: false,
    dropdownOptions: [],
    properties: [
        {
            label: "Component Name",
            identifier: "componentName",
            description: "Name of the component",
            type: OptionType.STRING,
            defaultValue: "",
            icon: "",
            enabled: true,
            required: false,
            allowDisable: false,
            properties: [],
            dropdownOptions: [],
        },
        {
            label: "Component Slug",
            identifier: "componentSlug",
            description: "Slug of the component",
            type: OptionType.STRING,
            defaultValue: "",
            icon: "",
            enabled: true,
            required: false,
            allowDisable: false,
            properties: [],
            dropdownOptions: [],
        },
        {
            label: "Props",
            identifier: "props",
            description: "",
            dropdownOptions: [],
            type: OptionType.COLLECTION,
            defaultValue: "",
            icon: "",
            enabled: true,
            required: false,
            allowDisable: false,
            properties: [
                {
                    label: "Type",
                    identifier: "type",
                    description: "",
                    type: OptionType.DROPDOWN,
                    defaultValue: "",
                    icon: "",
                    enabled: true,
                    required: false,
                    allowDisable: false,
                    dropdownOptions: [{ label: "String", value: "string" }],
                    properties: [],
                },
                {
                    label: "Name",
                    identifier: "name",
                    description: "",
                    type: OptionType.STRING,
                    defaultValue: "",
                    icon: "",
                    enabled: true,
                    required: false,
                    allowDisable: false,
                    dropdownOptions: [],
                    properties: [],
                },
                {
                    label: "Desc",
                    identifier: "desc",
                    description: "",
                    type: OptionType.STRING,
                    defaultValue: "",
                    icon: "",
                    enabled: true,
                    required: false,
                    allowDisable: false,
                    dropdownOptions: [],
                    properties: [],
                },
            ],
        },
        {
            label: "Tests",
            identifier: "tests",
            description: "",
            type: OptionType.INSTANCE,
            defaultValue: "",
            icon: "",
            enabled: true,
            required: false,
            allowDisable: true,
            dropdownOptions: [],
            properties: [
                {
                    label: "Test Type",
                    identifier: "testType",
                    description: "",
                    type: OptionType.DROPDOWN,
                    defaultValue: "",
                    icon: "",
                    enabled: true,
                    required: false,
                    allowDisable: false,
                    dropdownOptions: [
                        { value: "table", label: "Table Test" },
                        { value: "snapshot", label: "Snapshot Test" },
                    ],
                    properties: [],
                },
            ],
        },
    ],
};

export const ComponentBuilderConfigurationGroupPropertySingleText: ConfigurationGroupProperty = {
    label: "Component Name",
    identifier: "componentName",
    description: "Name of the component",
    type: OptionType.STRING,
    defaultValue: "",
    icon: "",
    enabled: true,
    required: false,
    allowDisable: false,
    properties: [],
    dropdownOptions: [],
};

export const ComponentBuilderConfigurationGroupPropertySingleDropdown: ConfigurationGroupProperty = {
    label: "Dropdown Test",
    identifier: "dropdownTest",
    description: "Dropdown Testing",
    type: OptionType.DROPDOWN,
    defaultValue: "",
    icon:
        "https://res.cloudinary.com/codotype/image/upload/v1558931014/product-logos/twitter-512.png",
    enabled: true,
    required: false,
    allowDisable: false,
    properties: [],
    dropdownOptions: [
        {
            value: "OPTION_01",
            label: "One",
        },
        { value: "OPTION_02", label: "Two" },
    ],
};

export const ComponentBuilderConfigurationGroupPropertySingleNumber: ConfigurationGroupProperty = {
    label: "Number Test",
    identifier: "numberTest",
    description:
        "This is a number for testing. Don't overthink it. It's just a number. I'll should pull some configuration options from an existing generator to populate this placeholder.",
    type: OptionType.NUMBER,
    defaultValue: "",
    icon: "",
    enabled: true,
    required: false,
    allowDisable: false,
    properties: [],
    dropdownOptions: [],
};

export const ComponentBuilderConfigurationGroupPropertyWithInstance01: ConfigurationGroupProperty = {
    label: "RandomInstanceTest",
    identifier: "random_instance",
    description: "",
    type: OptionType.INSTANCE,
    defaultValue: "",
    icon: "",
    enabled: true,
    required: false,
    allowDisable: true,
    dropdownOptions: [],
    properties: [ComponentBuilderConfigurationGroupPropertySingleDropdown],
};

export const ComponentBuilderConfigurationGroupPropertyWithInstance: ConfigurationGroupProperty = {
    label: "Tests",
    identifier: "tests",
    description: "",
    type: OptionType.INSTANCE,
    defaultValue: "",
    icon:
        "https://res.cloudinary.com/codotype/image/upload/v1558931014/product-logos/twitter-512.png",
    enabled: true,
    required: false,
    allowDisable: true,
    dropdownOptions: [],
    properties: [
        ComponentBuilderConfigurationGroupPropertySingleDropdown,
        ComponentBuilderConfigurationGroupPropertySingleText,
        {
            label: "Nested Instance",
            identifier: "nested_instance",
            description: "",
            type: OptionType.INSTANCE,
            defaultValue: "",
            icon: "",
            enabled: true,
            required: false,
            allowDisable: true,
            dropdownOptions: [],
            properties: [
                ComponentBuilderConfigurationGroupPropertySingleText,
                ComponentBuilderConfigurationGroupPropertySingleDropdown,
                ComponentBuilderConfigurationGroupPropertyWithInstance01,
            ],
        },
    ],
};

export const ComponentBuilderConfigurationGroup: ConfigurationGroup = {
    label: "Component Generator",
    identifier: "components_group",
    description: "Generate React components",
    enabled: true,
    allowDisable: false,
    variant: "",
    scope: "",
    properties: [
        ComponentBuilderConfigurationGroupPropertySingleText,
        ComponentBuilderConfigurationGroupPropertySingleNumber,
        ComponentBuilderConfigurationGroupPropertySingleDropdown,
        ComponentBuilderConfigurationGroupPropertyWithInstance,
        // ComponentBuilderConfigurationGroupProperty,
    ],
};
